sous-chefs/repo-management

- scripts/update_labels.sh
Useful script we used to remove all labels, may be of use again in the future?
Not sure if this is the right place though?
> Script for label removal

- Dangerfile
- README.md
- scripts/add_codeowners_if_not_present.rb
- scripts/git_branch_commit_push.sh
- scripts/open_pull_requests.rb
- scripts/watch_repos.rb
Adds some documentation on the scripts here
> Add readme about handy scripts

- scripts/add_codeowners_if_not_present.rb
codeowners team reference needs an @ mention
> Fix codeowners

- .gitattributes
- Dangerfile
- scripts/circleci_maker.rb
> Circleci config builder

- scripts/circleci_maker.rb
Makes the circleci config generator yaml lint compliant
> Yaml Lint compliant generator

- standardfiles/cookbook/.gitignore
- standardfiles/cookbook/chefignore
Better match what the chef cli generates
Signed-off-by: Tim Smith <tsmith@chef.io>
> Update the .gitignore and chefignore

- labels/cookbook/Good First Issue.json
- labels/cookbook/Help Wanted.json
- labels/cookbook/In Progress.json
- labels/cookbook/Maintenance.json
- labels/cookbook/Needs Triage.json
- labels/cookbook/On Hold.json
- labels/cookbook/Priority High.json
- labels/cookbook/Priority Low.json
- labels/cookbook/Priority Medium.json
- labels/cookbook/Regression.json
- labels/cookbook/Table Flip.json
- labels/cookbook/Tech Debt.json
- labels/cookbook/Unsupported.json
- labels/cookbook/Upstream Bug.json
- labels/cookbook/Waiting on Contributor.json
- labels/cookbook/bug.json
- labels/cookbook/documentation.json
- labels/cookbook/duplicate.json
- labels/cookbook/feature request.json
- labels/cookbook/hacktoberfest.json
Adds labels which can be used for management
> Add cookbook labels for management

- labels/cookbook/Release Major.json
- labels/cookbook/Release Minor.json
- labels/cookbook/Release Patch.json
- labels/cookbook/release.json
Add major, minor and patch labels to all repos
All labels are pink and it's the best thing.
None
> Add major, minor and patch labels to all repos

- standardfiles/cookbook/.github/workflows/md-links.yml
Adds link checker for documentation files.
> Add link validator for markdown

- standardfiles/cookbook/.yamllint
Add standardised yamllint
Yamllint wasn't managed anywhere. It really shouldn't need to be changed per repo
> Add standardised yamllint

- standardfiles/cookbook/chefignore
Make sure we ignore some more files that we ship in all our repos
Signed-off-by: Tim Smith <tsmith@chef.io>
> Update the contents of the chefignore to the latest

- standardfiles/cookbook/chefignore
Make sure we ship the changelog, but skip all our other CI files
Signed-off-by: Tim Smith <tsmith@chef.io>
> Update the files in the chefignore

- labels/cookbook/Close.json
- labels/cookbook/Stale.json
- labels/cookbook/spam.json
Adds labels for stale and close to Xorimabot
> Add labels to cover closing and stale issues

- standardfiles/cookbook/.editorconfig
- standardfiles/cookbook/.gitignore
Add comments to the editor config explaining what each thing does
Better organize the gitignore lines
Signed-off-by: Tim Smith <tsmith@chef.io>
> Update gitignore and editorconfig

- standardfiles/cookbook/.delivery/project.toml
> Stop using remote delivery file (#52)

- labels/cookbook/Skip Announce.json
- labels/cookbook/kind_build.json
- labels/cookbook/kind_chore.json
- labels/cookbook/kind_ci.json
- labels/cookbook/kind_docs.json
- labels/cookbook/kind_feature.json
- labels/cookbook/kind_fix.json
- labels/cookbook/kind_performance.json
- labels/cookbook/kind_refactor.json
- labels/cookbook/kind_style.json
- labels/cookbook/kind_test.json
- labels/cookbook/size_huge.json
- labels/cookbook/size_large.json
- labels/cookbook/size_medium.json
- labels/cookbook/size_small.json
- labels/cookbook/size_tiny.json
- Adds in the Skip Label
- Deletes old labels no longer used
Signed-off-by: Jason Field <jason@avon-lea.co.uk>
> Skip Label & Cleanup

- standardfiles/cookbook/.github/workflows/md-links.yml
- standardfiles/ide/.github/workflows/ci.yml
- standardfiles/terraform/.github/workflows/ci.yml
- standardfiles/terraform/.github/workflows/terraform-lint.yml
Describe what this change achieves
> Use v3 to checkout

- .github/workflows/ci.yml
- README.md
- renovate.json
- standardfiles/cookbook/renovate.json
Signed-off-by: Dan Webb <dan.webb@damacus.io>
Add Renovate Configuration
> Add Renovate Configuration

- standardfiles/cookbook/.markdownlint-cli2.yaml
Signed-off-by: Lance Albertson <lance@osuosl.org>
Describe what this change achieves
> Remove extra newline to fix yamlint errors

- README.md
- scripts/git_branch_commit_push.sh
- scripts/open_pull_requests.rb
- standardfiles/cookbook/CONTRIBUTING.md
- standardfiles/cookbook/TESTING.md
Rename `master` to `main` in scripts and docs.
None
(not applicable)
- ~A summary of changes made is included in the CHANGELOG under `## Unreleased`~
- ~New functionality includes testing.~
- ~New functionality has been documented in the README if applicable.~
> Change "master" to "main" in files

- standardfiles/cookbook/.markdownlint-cli2.yaml
This is started to be in repos such as postgresql and conflicts with CI tests.
Signed-off-by: Lance Albertson <lance@osuosl.org>
Describe what this change achieves
> Ignore copilot instructions with markdownlint

- standardfiles/cookbook/kitchen.dokken.yml
Signed-off-by: Lance Albertson <lance@osuosl.org>
Describe what this change achieves
> Add almalinux-10 and centos-stream-10 dokken images

- standardfiles/cookbook/.vscode/extensions.json
previous extension has been deprecated and recommends ruby-lsp now.
> Update extensions.json standardized files

- .yamllint
Relaxing yamllint
Hopefully triggering repo-sync-action
> Relax our yamllint rules
